//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Interface1")]
    public interface Interface1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/getUpdate", ReplyAction="http://tempuri.org/Interface1/getUpdateResponse")]
        string getUpdate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/getUpdate", ReplyAction="http://tempuri.org/Interface1/getUpdateResponse")]
        System.Threading.Tasks.Task<string> getUpdateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/getDelete", ReplyAction="http://tempuri.org/Interface1/getDeleteResponse")]
        string getDelete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Interface1/getDelete", ReplyAction="http://tempuri.org/Interface1/getDeleteResponse")]
        System.Threading.Tasks.Task<string> getDeleteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Interface1Channel : Assignment3.ServiceReference1.Interface1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Interface1Client : System.ServiceModel.ClientBase<Assignment3.ServiceReference1.Interface1>, Assignment3.ServiceReference1.Interface1 {
        
        public Interface1Client() {
        }
        
        public Interface1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Interface1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Interface1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Interface1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getUpdate() {
            return base.Channel.getUpdate();
        }
        
        public System.Threading.Tasks.Task<string> getUpdateAsync() {
            return base.Channel.getUpdateAsync();
        }
        
        public string getDelete() {
            return base.Channel.getDelete();
        }
        
        public System.Threading.Tasks.Task<string> getDeleteAsync() {
            return base.Channel.getDeleteAsync();
        }
    }
}
